CREATE TABLE users(
  user_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(20) NOT NULL,
  name VARCHAR(20) NOT NULL,
  user_age SMALLINT,
  privilege_lvl TINYINT NOT NULL DEFAULT 1,
  sign_up_date DATE NOT NULL
)ENGINE=INNODB AUTO_INCREMENT=10000000 DEFAULT CHARSET=utf8 COMMENT='用户表';
  
  
