CREATE TABLE users(
  userid BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '用户ID',
  username VARCHAR(20) NOT NULL UNIQUE KEY COMMENT '用户名',
  nickname VARCHAR(20) NOT NULL UNIQUE KEY COMMENT '昵称',
  age SMALLINT COMMENT '年龄',
  privilege_lvl TINYINT NOT NULL DEFAULT 1 COMMENT '权限等级',
  sign_up_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMPT '注册日期'
)ENGINE=INNODB AUTO_INCREMENT=10000000 DEFAULT CHARSET=utf8 COMMENT='用户表';

CREATE TABLE privilege_lvls(
  lvl TINYINT PRIMARY KEY COMMENT '等级',
  role VARCHAR(10) NOT NULL COMMENT '角色'
)ENGINE=INNODB CHARSET=utf8 COMMENT='角色表';

CREATE TABLE blocks(
  blockid SMALLINT AUTO_INCREMENT PRIMARY KEY COMMENT '板块ID',
  blockname VARCHAR(20) NOT NULL UNIQUE KEY COMMENT '板块名',
  father_blockid SAMLLINT NOT NULL COMMENT '父板块ID'
)
CREATE TABLE posts(
  postid INT AUTO_INCRREMENT PRIMARY KEY COMMENT '帖子ID',
  posterid VARCHAR(20) NOT NULL UNIQUE KEY COMMENT '发帖人ID',
  post_time'发帖时间'
)
  
