CREATE TABLE users(
  userid BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '用户ID',
  username VARCHAR(20) NOT NULL UNIQUE KEY COMMENT '用户名',
  nickname VARCHAR(20) NOT NULL UNIQUE KEY COMMENT '昵称',
  age SMALLINT COMMENT '年龄',
  privilege_lvl TINYINT NOT NULL DEFAULT 1 COMMENT '权限等级',
  sign_up_date DATE NOT NULL COMMENT '注册日期'
)ENGINE=INNODB AUTO_INCREMENT=10000000 DEFAULT CHARSET=utf8 COMMENT='用户表';

CREATE TABLE privilege_lvl(
  lvl TINYINT PRIMARY KEY COMMENT '等级',
  role VARCHAR(10) NOT NULL COMMENT '角色'
)ENGINE=INNODB CHARSET=utf8 COMMENT='角色表';

  
