CREATE TABLE users(
  user_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '用户ID',
  user_name VARCHAR(20) NOT NULL UNIQUE COMMENT '用户名',
  nick_name VARCHAR(20) NOT NULL UNIQUE COMMENT '昵称',
  age SMALLINT COMMENT '年龄',
  email VARCHAR(40) NOT NULL UNIQUE COMMENT '邮箱',
  md5 VARCHAR(40) NOT NULL COMMENT '邮箱验证码',
  validated TINYINT NOT NULL DEFAULT 0 COMMENT '验证状态',
  privilege_lvl TINYINT NOT NULL DEFAULT 1 COMMENT '权限等级',
  lvl TINYINT NOT NULL DEFUALT 1 COMMENT '用户等级',
  head_img VARCHAR(20) NOT NULL COMMENT '头像',
  sign_up_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间'
)ENGINE=INNODB AUTO_INCREMENT=10000000 DEFAULT CHARSET=utf8 COMMENT='用户表';

CREATE TABLE privilege_lvls(
  lvl TINYINT PRIMARY KEY COMMENT '等级',
  role VARCHAR(10) NOT NULL UNIQUE COMMENT '角色'
)ENGINE=INNODB CHARSET=utf8 COMMENT='角色表';

CREATE TABLE lvl_names(
  lvl TINY PRIMARY KEY COMMENT '等级',
  name VARCHAR(20) NOT NULL UNIQUE COMMENNT '称号'
)

CREATE TABLE blocks(
  block_id SMALLINT AUTO_INCREMENT PRIMARY KEY COMMENT '板块ID',
  block_name VARCHAR(20) NOT NULL UNIQUE COMMENT '板块名',
  father_block_id SAMLLINT NOT NULL DEFAULT 0 COMMENT '父板块ID'
)ENGINE=INNODB CHARSET=utf8 COMMENT='板块表';

CREATE TABLE posts(
  post_id INT AUTO_INCREMENT PRIMARY KEY COMMENT '主题帖ID',
  post_title VARCHAR(40) NOT NULL COMMENT '主题帖标题',
  block_id SMALLINT NOT NULL COMMENT '所属板块ID',
  poster_id BIGINT NOT NULL COMMENT '发帖人ID',
  post_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMMENT '发帖时间'
)ENGINE=INNODB CHARSET=utf8 COMMENT='主题帖表';
  
CREATE TABLE comments(
  comment_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '留言ID',
  comment_value VARCHAR(225) NOT NULL COMMENT '留言内容',
  re_commentid BIGINT NOT NULL DEFAULT 0 COMMENT '所回复的留言ID',
  post_id INT NOT NULL COMMENT '所属主题帖ID',
  commenter_id BIGINT NOT NULL COMMENT '留言人ID',
  comment_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMMENT '留言时间'
)ENGINE=INNODB CHARSET=utf8 COMMENT='留言表';
